name: Selenium Grid Tests

on: [push]

jobs:

  test:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Start Selenium Grid
      run: docker-compose up -d

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Run Tests
      run: mvn test